### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by popopony** [Taiga74164/Akebi-GC#14]
[telemetry:0929/215625.218:ERROR:mihoyo_url_fetch_delegate.cc(22)] Json fetch request failed with error code: -1
[telemetry:0929/215625.218:ERROR:mihoyo_report_service_base.cc(345)] TelemetryServiceplat_explog_sdk_v2 : Http request failed. Response body:

**Comment by Taiga74164** [comment]
not a bug

**Comment by Taiga74164** [comment]
contact mihoyo customer service and ask them why
