### ISSUE TITLE
[Bug] Free Camera doesn't render the map pretty well

### ISSUE THREAD

**Issue by jsteve507** [Taiga74164/Akebi-GC#23]
## 2 Bugs On Free Camera

1. In-Game Brightness (2.7 Feature) is always reset to default settings every time you activate the free camera.
2. The map doesn't render on depending where the camera location.

## How to reproduce this bug

Steps to reproduce this bug:
(Issue 1)
1. Make sure to set custom brightness setting than using default one.
2. Activate Free Camera on Akebi-GC

(Issue 2)
1. Activate Free Camera on Akebi-GC
2. Make sure to disable player input, so it doesn't move whenever you use the free camera.
3. Go far away from the player model.

## Expectation
Issue 1 = Brightness settings stay whenever you activate the free camera
Issue 2 = The map renders wherever the camera is located/moved.

## Screenshot/Video
Issue 1: I think, i don't need to screenshot it (I hope, you get what i meant)
Issue 2: Here's below
![image](https://user-images.githubusercontent.com/70462309/193977715-e81683a1-19fe-4a11-9db9-e976b06a54a8.png)

## Your device information
 - System information: Windows 11 (64-Bit) Build 22H2
 - Version: 1.0.0 (For GI 3.1)

## Additional information
If those 2 issues cannot be fixed. Here's what i think, make noclip as alternative option. Current state, it doesn't have smoothness option, speed option and FoV option.

**Comment by Taiga74164** [comment]
yeah well youre far from that area and for now the only way I found was to render objects such as trees, barrels, etc. but it still doesnt fully render the terrains and stuff

**Comment by jsteve507** [comment]
> yeah well youre far from that area and for now the only way I found was to render objects such as trees, barrels, etc. but it still doesnt fully render the terrains and stuff

I see. If this is not fixable. Could you add features into the noclip: make player model invisible, and adding from free camera features (smoothness option, speed option, FoV option)? This way, the map will always be rendered, since the player model stays on the camera (even if this player model is invisible).

**Comment by Bilx-ZL** [comment]
2 is not a bug.

**Comment by jsteve507** [comment]
> 2 is not a bug.

what do you mean with this? from user perspective.. it's in fact a bug. I know, this isn't a fixable issue. That's why i put alternative solution above.

**Comment by Julienraptor01** [comment]
> > 2 is not a bug.
> 
> what do you mean with this? from user perspective.. it's in fact a bug. I know, this isn't a fixable issue. That's why i put alternative solution above.

2 isn't a bug, the map render based on the player position, and this is great to be able to see low res terrain, move out of the skybox etc

**Comment by Bilx-ZL** [comment]
> > 2 is not a bug.
> 
> what do you mean with this? from user perspective.. it's in fact a bug. I know, this isn't a fixable issue. That's why i put alternative solution above.

i had see your solution ,you want your character follow the free camera position for render the map perfectely, but i guess it would get a ban .. because the server maybe see your charactor flying very fast in the sky.

**Comment by jsteve507** [comment]
> > > 2 is not a bug.
> > 
> > 
> > what do you mean with this? from user perspective.. it's in fact a bug. I know, this isn't a fixable issue. That's why i put alternative solution above.
> 
> i had see your solution ,you want your character follow the free camera position for render the map perfectely, but i guess it would get a ban .. because the server maybe see your charactor flying very fast in the sky.

why would someone need to use this on official server? it's clearly a risk to use something like this kind of tool. There's a plenty of PS already, even there's a popular and safer one that i could suggest you to play.

**Comment by Bilx-ZL** [comment]
> 

why you think everyone use this only play on PS？ if you only playon PS，most features of this tool are not necessary.

**Comment by jsteve507** [comment]
> > 
> 
> why you think everyone use this only play on PS？ if you only playon PS，most features of this tool are not necessary.

Why would you think that? Everyone have different reason to use that. Stop saying that you know everything. I can say one of the reason.. Testing the characters, content creation, modding, etc..

**Comment by Bilx-ZL** [comment]
> why would someone need to use this on official server?

“why would someone need to use this on official server?”. that's you said. you think nobody use it play on official serevr, like this tool is specially customized for you and you PS.  you are the one who is most like "know everything".

**Comment by Julienraptor01** [comment]
> > > 
> > 
> > why you think everyone use this only play on PS？ if you only playon PS，most features of this tool are not necessary.
> 
> Why would you think that? Everyone have different reason to use that. Stop saying that you know everything. I can say one of the reason.. Testing the characters, content creation, modding, etc..

Yes it can also be used on ps, it has uses on both

**Comment by chiqors** [comment]
I don't think, @jsteve507 intends to replace the existing features of the current freecam (read again about his alternative solution).  Instead it should be a new option, added to the tool for people who want to use this with the map being rendered as they go (of course, you should ONLY activate this on PS)
