### ISSUE TITLE
[Suggestion] Supports of multiple languages

### ISSUE THREAD

**Issue by Moss-Tony** [Taiga74164/Akebi-GC#26]
Because many terms can be difficult for non-native speakers to understand. Hope to add support with multiple languages.

Work steps:
1. open source text
2. Recruit volunteers to upload translation by pr or discord etc.

**Comment by RUInalan** [comment]
+1

**Comment by Gsutab-M** [comment]
I don't know where to change it
  :(

**Comment by Julienraptor01** [comment]
I could do a french translation if we get translatable strings

**Comment by sabala** [comment]
maybe Taiga and contribuitors can open a [crowdin](https://crowdin.com/) for us.

**Comment by huwcheng** [comment]
什么时候支持中文，英语很多看不懂啊！The software must be adapted to the Chinese language

**Comment by Taiga74164** [comment]
no. we dont care
