### ISSUE TITLE
[Help]

### ISSUE THREAD

**Issue by iamsisterlover** [Taiga74164/Akebi-GC#30]
My English is a little bad, don't mind.First,I've been banned.When I used the latest version and changed the game resolution from full screen to windowin,But version 1.0 was not banned,So I guess is the resolution of the game or a new version of the problem,and I had been using it for two weeks before that and had been banned,

--------------------------------------------------------------------------------------------------------------------------------
II'm hoping to get a reply, that's all.
-------------------------------------------------------------------------------------------------------------------------------
![image](https://user-images.githubusercontent.com/116266440/196915304-ceed49f9-b640-4a85-8200-f270e06777a9.png)
------------------------------------------------------------------------------------------------
The System isWindows10
 --------------------------------------------------------
the version is china-1.05
--------------------------------------------------------
In conclusion, I would like to say that I would be very grateful if I could receive a reply****

**Comment by Gsutab-M** [comment]
是有什么问题吗？

**Comment by iamsisterlover** [comment]
> 是有什么问题吗？

用了半个月，挺好用的，一些小bug不足以掩盖他的强大，不过这次主要是我上午使用了1.05版本，然后下午就打着突然被封了，中间唯一的变化大概就是我更新了新版本和更改了游戏分辨率，另外小提一件事，1.0版本是游戏开始时显示菜单然后游戏加载数据，1.05版本是游戏数据加载好后，菜单才显示出来XD

**Comment by Gsutab-M** [comment]
> > 是有什么问题吗？
> 
> 用了半个月，挺好用的，一些小bug不足以掩盖他的强大，不过这次主要是我上午使用了1.05版本，然后下午就打着突然被封了，中间唯一的变化大概就是我更新了新版本和更改了游戏分辨率，另外小提一件事，1.0版本是游戏开始时显示菜单然后游戏加载数据，1.05版本是游戏数据加载好后，菜单才显示出来XD

封号是正常的，我也是被封过一次了

**Comment by iamsisterlover** [comment]
> > > 是有什么问题吗？
> > 
> > 
> > 用了，我刚才用了的，一些小虫子用了典型的说话方式是我的，不过今天上午 1.05 左右，然后今天上午的情况就差不多了新版本和更改了游戏版本时，1.00000000版本开始显示新版本的游戏，然后显示新版本的游戏，1.0000版本是游戏数据，1.0版本是数据加载好之后，菜单才D
> 
> 封号是正常的，我也是被封过一次了
是的，现在第二个号也被封了XD，退游了

**Comment by Gsutab-M** [comment]
> > > > 是有什么问题吗？
> > > 
> > > 
> > > 用了，我刚才用了的，一些小虫子用了典型的说话方式是我的，不过今天上午 1.05 左右，然后今天上午的情况就差不多了新版本和更改了游戏版本时，1.00000000版本开始显示新版本的游戏，然后显示新版本的游戏，1.0000版本是游戏数据，1.0版本是数据加载好之后，菜单才D
> > 
> > 
> > 封号是正常的，我也是被封过一次了
> > 是的，现在第二个号也被封了XD，退游了


> > > > 是有什么问题吗？
> > > 
> > > 
> > > 用了，我刚才用了的，一些小虫子用了典型的说话方式是我的，不过今天上午 1.05 左右，然后今天上午的情况就差不多了新版本和更改了游戏版本时，1.00000000版本开始显示新版本的游戏，然后显示新版本的游戏，1.0000版本是游戏数据，1.0版本是数据加载好之后，菜单才D
> > 
> > 
> > 封号是正常的，我也是被封过一次了
> > 是的，现在第二个号也被封了XD，退游了

我的号昨天被封禁了15年，我也退游了，顺便把号注销了

**Comment by Gsutab-M** [comment]
> > > > > 是有什么问题吗？
> > > > 
> > > > 
> > > > 用了，我刚才用了的，一些小虫子用了典型的说话方式是我的，不过今天上午 1.05 左右，然后今天上午的情况就差不多了新版本和更改了游戏版本时，1.00000000版本开始显示新版本的游戏，然后显示新版本的游戏，1.0000版本是游戏数据，1.0版本是数据加载好之后，菜单才D
> > > 
> > > 
> > > 封号是正常的，我也是被封过一次了
> > > 是的，现在第二个号也被封了XD，退游了
> 
> > > > > 是有什么问题吗？
> > > > 
> > > > 
> > > > 用了，我刚才用了的，一些小虫子用了典型的说话方式是我的，不过今天上午 1.05 左右，然后今天上午的情况就差不多了新版本和更改了游戏版本时，1.00000000版本开始显示新版本的游戏，然后显示新版本的游戏，1.0000版本是游戏数据，1.0版本是数据加载好之后，菜单才D
> > > 
> > > 
> > > 封号是正常的，我也是被封过一次了
> > > 是的，现在第二个号也被封了XD，退游了
> 
> 我的号昨天被封禁了15年，我也退游了，顺便把号注销了

但是我还是换了个号继续这样折腾

**Comment by liaorw** [comment]
40m自动拾取，还这么短时间，不封才怪

**Comment by Gsutab-M** [comment]
> 40m自动拾取，还这么短时间，不封才怪

我认为是开了攻速和游戏加速的问题
