### ISSUE TITLE
[Suggestion] Open language code adaptation

### ISSUE THREAD

**Issue by huwcheng** [Taiga74164/Akebi-GC#37]
## 能否开源语言代码区域，我想进行汉化，在下载的源文件都找不到代码

Can open source language code area, I want to Chinese.The code was not found in any of the downloaded source files
![image](https://user-images.githubusercontent.com/114603906/197552103-f40e1e8b-0476-45ae-a596-cbd43bc97c5f.png)

![1666621714883](https://user-images.githubusercontent.com/114603906/197551442-9ee6174d-c863-4aba-aa9b-f030f62928ac.jpg)

**Comment by Taiga74164** [comment]
good luck lol
