### ISSUE TITLE
I can't use cheat, because it's not updated

### ISSUE THREAD

**Issue by sevasee66** [Taiga74164/Akebi-GC#38]
![image](https://user-images.githubusercontent.com/59143880/197557366-b0a280cd-7a42-40a7-8981-844b7fb46969.png)

**Comment by iamsisterlover** [comment]
yeah,We should Improve our technical level so that we can do more and know more( Just for the original code？XD ),do it,and you can cheat again.

**Comment by Taiga74164** [comment]
dumbass
